//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueTupleOfInt32StringStringInt32", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ValueTupleOfInt32StringStringInt32 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Item1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item3Field;
        
        private int Item4Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Item1 {
            get {
                return this.Item1Field;
            }
            set {
                if ((this.Item1Field.Equals(value) != true)) {
                    this.Item1Field = value;
                    this.RaisePropertyChanged("Item1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Item2 {
            get {
                return this.Item2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Item2Field, value) != true)) {
                    this.Item2Field = value;
                    this.RaisePropertyChanged("Item2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Item3 {
            get {
                return this.Item3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Item3Field, value) != true)) {
                    this.Item3Field = value;
                    this.RaisePropertyChanged("Item3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Item4 {
            get {
                return this.Item4Field;
            }
            set {
                if ((this.Item4Field.Equals(value) != true)) {
                    this.Item4Field = value;
                    this.RaisePropertyChanged("Item4");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueTupleOfStringStringStringInt32", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ValueTupleOfStringStringStringInt32 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item3Field;
        
        private int Item4Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Item1 {
            get {
                return this.Item1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Item1Field, value) != true)) {
                    this.Item1Field = value;
                    this.RaisePropertyChanged("Item1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Item2 {
            get {
                return this.Item2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Item2Field, value) != true)) {
                    this.Item2Field = value;
                    this.RaisePropertyChanged("Item2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Item3 {
            get {
                return this.Item3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Item3Field, value) != true)) {
                    this.Item3Field = value;
                    this.RaisePropertyChanged("Item3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Item4 {
            get {
                return this.Item4Field;
            }
            set {
                if ((this.Item4Field.Equals(value) != true)) {
                    this.Item4Field = value;
                    this.RaisePropertyChanged("Item4");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Tema2.ServiceReference1.HelloWorldResponse HelloWorld(Tema2.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Tema2.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name ReadResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Read", ReplyAction="*")]
        Tema2.ServiceReference1.ReadResponse Read(Tema2.ServiceReference1.ReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Read", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2.ServiceReference1.ReadResponse> ReadAsync(Tema2.ServiceReference1.ReadRequest request);
        
        // CODEGEN: Generating message contract since element name Univ from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        Tema2.ServiceReference1.CreateResponse Create(Tema2.ServiceReference1.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2.ServiceReference1.CreateResponse> CreateAsync(Tema2.ServiceReference1.CreateRequest request);
        
        // CODEGEN: Generating message contract since element name UpdateUniv from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        Tema2.ServiceReference1.UpdateResponse Update(Tema2.ServiceReference1.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2.ServiceReference1.UpdateResponse> UpdateAsync(Tema2.ServiceReference1.UpdateRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        Tema2.ServiceReference1.DeleteResponse Delete(Tema2.ServiceReference1.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2.ServiceReference1.DeleteResponse> DeleteAsync(Tema2.ServiceReference1.DeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Tema2.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Tema2.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Tema2.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Read", Namespace="http://tempuri.org/", Order=0)]
        public Tema2.ServiceReference1.ReadRequestBody Body;
        
        public ReadRequest() {
        }
        
        public ReadRequest(Tema2.ServiceReference1.ReadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadRequestBody {
        
        public ReadRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2.ServiceReference1.ReadResponseBody Body;
        
        public ReadResponse() {
        }
        
        public ReadResponse(Tema2.ServiceReference1.ReadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema2.ServiceReference1.ArrayOfString ReadResult;
        
        public ReadResponseBody() {
        }
        
        public ReadResponseBody(Tema2.ServiceReference1.ArrayOfString ReadResult) {
            this.ReadResult = ReadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create", Namespace="http://tempuri.org/", Order=0)]
        public Tema2.ServiceReference1.CreateRequestBody Body;
        
        public CreateRequest() {
        }
        
        public CreateRequest(Tema2.ServiceReference1.CreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema2.ServiceReference1.ValueTupleOfInt32StringStringInt32 Univ;
        
        public CreateRequestBody() {
        }
        
        public CreateRequestBody(Tema2.ServiceReference1.ValueTupleOfInt32StringStringInt32 Univ) {
            this.Univ = Univ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2.ServiceReference1.CreateResponseBody Body;
        
        public CreateResponse() {
        }
        
        public CreateResponse(Tema2.ServiceReference1.CreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateResponseBody {
        
        public CreateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public Tema2.ServiceReference1.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(Tema2.ServiceReference1.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema2.ServiceReference1.ValueTupleOfStringStringStringInt32 UpdateUniv;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(Tema2.ServiceReference1.ValueTupleOfStringStringStringInt32 UpdateUniv) {
            this.UpdateUniv = UpdateUniv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2.ServiceReference1.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(Tema2.ServiceReference1.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public Tema2.ServiceReference1.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(Tema2.ServiceReference1.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2.ServiceReference1.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(Tema2.ServiceReference1.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteResponseBody {
        
        public DeleteResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Tema2.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Tema2.ServiceReference1.WebService1Soap>, Tema2.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2.ServiceReference1.HelloWorldResponse Tema2.ServiceReference1.WebService1Soap.HelloWorld(Tema2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Tema2.ServiceReference1.HelloWorldRequest inValue = new Tema2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Tema2.ServiceReference1.HelloWorldRequestBody();
            Tema2.ServiceReference1.HelloWorldResponse retVal = ((Tema2.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2.ServiceReference1.HelloWorldResponse> Tema2.ServiceReference1.WebService1Soap.HelloWorldAsync(Tema2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Tema2.ServiceReference1.HelloWorldRequest inValue = new Tema2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Tema2.ServiceReference1.HelloWorldRequestBody();
            return ((Tema2.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2.ServiceReference1.ReadResponse Tema2.ServiceReference1.WebService1Soap.Read(Tema2.ServiceReference1.ReadRequest request) {
            return base.Channel.Read(request);
        }
        
        public Tema2.ServiceReference1.ArrayOfString Read() {
            Tema2.ServiceReference1.ReadRequest inValue = new Tema2.ServiceReference1.ReadRequest();
            inValue.Body = new Tema2.ServiceReference1.ReadRequestBody();
            Tema2.ServiceReference1.ReadResponse retVal = ((Tema2.ServiceReference1.WebService1Soap)(this)).Read(inValue);
            return retVal.Body.ReadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2.ServiceReference1.ReadResponse> Tema2.ServiceReference1.WebService1Soap.ReadAsync(Tema2.ServiceReference1.ReadRequest request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2.ServiceReference1.ReadResponse> ReadAsync() {
            Tema2.ServiceReference1.ReadRequest inValue = new Tema2.ServiceReference1.ReadRequest();
            inValue.Body = new Tema2.ServiceReference1.ReadRequestBody();
            return ((Tema2.ServiceReference1.WebService1Soap)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2.ServiceReference1.CreateResponse Tema2.ServiceReference1.WebService1Soap.Create(Tema2.ServiceReference1.CreateRequest request) {
            return base.Channel.Create(request);
        }
        
        public void Create(Tema2.ServiceReference1.ValueTupleOfInt32StringStringInt32 Univ) {
            Tema2.ServiceReference1.CreateRequest inValue = new Tema2.ServiceReference1.CreateRequest();
            inValue.Body = new Tema2.ServiceReference1.CreateRequestBody();
            inValue.Body.Univ = Univ;
            Tema2.ServiceReference1.CreateResponse retVal = ((Tema2.ServiceReference1.WebService1Soap)(this)).Create(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2.ServiceReference1.CreateResponse> Tema2.ServiceReference1.WebService1Soap.CreateAsync(Tema2.ServiceReference1.CreateRequest request) {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2.ServiceReference1.CreateResponse> CreateAsync(Tema2.ServiceReference1.ValueTupleOfInt32StringStringInt32 Univ) {
            Tema2.ServiceReference1.CreateRequest inValue = new Tema2.ServiceReference1.CreateRequest();
            inValue.Body = new Tema2.ServiceReference1.CreateRequestBody();
            inValue.Body.Univ = Univ;
            return ((Tema2.ServiceReference1.WebService1Soap)(this)).CreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2.ServiceReference1.UpdateResponse Tema2.ServiceReference1.WebService1Soap.Update(Tema2.ServiceReference1.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(Tema2.ServiceReference1.ValueTupleOfStringStringStringInt32 UpdateUniv) {
            Tema2.ServiceReference1.UpdateRequest inValue = new Tema2.ServiceReference1.UpdateRequest();
            inValue.Body = new Tema2.ServiceReference1.UpdateRequestBody();
            inValue.Body.UpdateUniv = UpdateUniv;
            Tema2.ServiceReference1.UpdateResponse retVal = ((Tema2.ServiceReference1.WebService1Soap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2.ServiceReference1.UpdateResponse> Tema2.ServiceReference1.WebService1Soap.UpdateAsync(Tema2.ServiceReference1.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2.ServiceReference1.UpdateResponse> UpdateAsync(Tema2.ServiceReference1.ValueTupleOfStringStringStringInt32 UpdateUniv) {
            Tema2.ServiceReference1.UpdateRequest inValue = new Tema2.ServiceReference1.UpdateRequest();
            inValue.Body = new Tema2.ServiceReference1.UpdateRequestBody();
            inValue.Body.UpdateUniv = UpdateUniv;
            return ((Tema2.ServiceReference1.WebService1Soap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2.ServiceReference1.DeleteResponse Tema2.ServiceReference1.WebService1Soap.Delete(Tema2.ServiceReference1.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public void Delete(string name) {
            Tema2.ServiceReference1.DeleteRequest inValue = new Tema2.ServiceReference1.DeleteRequest();
            inValue.Body = new Tema2.ServiceReference1.DeleteRequestBody();
            inValue.Body.name = name;
            Tema2.ServiceReference1.DeleteResponse retVal = ((Tema2.ServiceReference1.WebService1Soap)(this)).Delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2.ServiceReference1.DeleteResponse> Tema2.ServiceReference1.WebService1Soap.DeleteAsync(Tema2.ServiceReference1.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2.ServiceReference1.DeleteResponse> DeleteAsync(string name) {
            Tema2.ServiceReference1.DeleteRequest inValue = new Tema2.ServiceReference1.DeleteRequest();
            inValue.Body = new Tema2.ServiceReference1.DeleteRequestBody();
            inValue.Body.name = name;
            return ((Tema2.ServiceReference1.WebService1Soap)(this)).DeleteAsync(inValue);
        }
    }
}
